# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07499b787f73e2f424ab379c527af5dbeaee45db755e06a6897d916a5c78239e6894f9a545d96cfafa0ebc958c358f70b15249c1adda4f3c38012f433163209

test:
  secret_key_base: aaf36e0dc58ccfe28922c7ae92e28e438cb6b5f0cd8925e5c0cbc75278e7b01d08f3a88e768907937b2fec4df5ddb05d7aa4d99ea1f42da5c4c0ec311a5bfdea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
